services:
  database:
    image: postgres:17.6
    restart: always
    ports:
      - "5433:5432"
#    volumes:
#      - /custom/mount:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
