server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: lunch
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
