addProduct:
  post:
    operationId: addProduct
    description: Add product to order
    parameters:
      - $ref: "../components/parameters.yaml#/UserIdHeader"
      - $ref: "../components/parameters.yaml#/OrderIdPath"
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../components/schemas.yaml#/ProductDetailsDto"
    responses:
      200:
        description: Product successfully added
      400:
        description: Invalid input
    tags:
      - product

manageProductDetails:
  put:
    operationId: editProductDetails
    description: Edit product details
    parameters:
      - $ref: "../components/parameters.yaml#/ProductIdPath"
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../components/schemas.yaml#/ProductDetailsDto"
    responses:
      200:
        description: Product details successfully edited
      400:
        description: Invalid input
    tags:
      - product
  post:
    operationId: copyProduct
    description: Copy product
    parameters:
      - $ref: "../components/parameters.yaml#/UserIdHeader"
      - $ref: "../components/parameters.yaml#/ProductIdPath"
      - $ref: "../components/parameters.yaml#/DestinationOrderIdQuery"
    responses:
      200:
        description: Product successfully copied
      404:
        description: Product with provided id does not found
    tags:
      - product
  delete:
    operationId: deleteProduct
    description: Delete product
    parameters:
      - $ref: "../components/parameters.yaml#/UserIdHeader"
      - $ref: "../components/parameters.yaml#/ProductIdPath"
    responses:
      200:
        description: Product successfully deleted
      404:
        description: Product with provided id does not found or already deleted
    tags:
      - product
