UserIdPath:
  name: id
  in: path
  required: true
  schema:
    type: integer
    format: int64

UserIdHeader:
  name: X-User-Id
  in: header
  required: true
  schema:
    type: integer
    format: int64
  description: ID of an authenticated user

TeamIdPath:
  name: teamId
  in: path
  required: true
  schema:
    type: integer
    format: int64

OrderIdPath:
  name: orderId
  in: path
  required: true
  schema:
    type: integer
    format: int64

ProductIdPath:
  mame: productId
  in: path
  required: true
  schema:
    type: integer
    format: int64