UserIdPath:
  name: id
  in: path
  required: true
  schema:
    type: integer
    format: int64

UserIdHeader:
  name: X-User-Id
  in: header
  required: true
  schema:
    type: integer
    format: int64
  description: ID of an authenticated user

TeamIdPath:
  name: teamId
  in: path
  required: true
  schema:
    type: integer
    format: int64

MemberIdPath:
  name: memberId
  in: path
  required: true
  schema:
    type: integer
    format: int64

UserRolePath:
  name: roleDto
  in: path
  required: true
  schema:
    $ref: "../components/schemas.yaml#/UserRoleDto"

OrderIdPath:
  name: orderId
  in: path
  required: true
  schema:
    type: integer
    format: int64

ProductIdPath:
  name: productId
  in: path
  required: true
  schema:
    type: integer
    format: int64

DestinationOrderIdQuery:
  name: destinationOrderId
  in: query
  required: true
  schema:
    type: integer
    format: int64

ProductOptionQuery:
  name: productOptionName
  in: query
  required: true
  schema:
    type: string
