---
openapi: 3.0.1
info:
  title: Lunch service API
  version: v1

servers:
  - url: /api/v1

paths:
  /user/{id}:
    $ref: "./paths/user.yaml#/getUser"

  /auth/signup:
    $ref: "./paths/auth.yaml#/signup"

  /auth/signin:
    $ref: "./paths/auth.yaml#/signIn"

  /team:
    $ref: "./paths/team.yaml#/team"

  /team/{teamId}/members:
    $ref: "./paths/team.yaml#/teamMembers"

components:
  schemas:
    UserRoleDto:
      $ref: "./components/schemas.yaml#/UserRoleDto"

    UserDto:
      $ref: "./components/schemas.yaml#/UserDto"

    SignupDto:
      $ref: "./components/schemas.yaml#/SignupDto"

    SignInDto:
      $ref: "./components/schemas.yaml#/SignInDto"

    CreateTeamRequest:
      $ref: "./components/schemas.yaml#/CreateTeamRequest"

    TeamDto:
      $ref: "./components/schemas.yaml#/TeamDto"


  parameters:
    UserIdPath:
      $ref: "./components/parameters.yaml#/UserIdPath"

    UserIdHeader:
      $ref: "./components/parameters.yaml#/UserIdHeader"
