---
openapi: 3.0.1
info:
  title: Lunch service API
  version: v1

servers:
  - url: /api/v1

paths:
  "/user/{id}":
    get:
      operationId: getUser
      description: Get user by id
      security:
        - BearerAuth: [ ]
      parameters:
        - $ref: '#/components/parameters/UserIdPath'
      responses:
        "200":
          description: User model
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDto"
      tags:
        - user

  "/auth/signup":
    post:
      operationId: signup
      description: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignupDto"
      responses:
        "201":
          description: User created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserDto"
      tags:
        - auth

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserRoleDto:
      description: User role enum
      type: string
      enum:
        - ADMIN
        - USER
        - GUEST

    UserDto:
      description: User object
      type: object
      required:
        - id
        - firstName
        - lastName
        - username
        - email
      properties:
        id:
          type: integer
          format: int64
        firstName:
          type: string
        lastName:
          type: string
        username:
          type: string
        email:
          type: string

    SignupDto:
      description: Data for user registration
      type: object
      required:
        - username
        - password
        - firstName
        - lastName
        - email
      properties:
        username:
          type: string
        password:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string

    # Authentication
    CredentialsDto:
      description: User sign-in credentials
      type: object
      properties:
        username:
          type: string
        password:
          type: string

  parameters:
    UserIdPath:
      name: id
      in: path
      required: true
      schema:
        type: integer
        format: int64
