---
openapi: 3.0.1
info:
  title: Lunch service API
  version: v1

servers:
  - url: /api/v1

paths:

  # User paths
  /user/{id}:
    $ref: "./paths/user.yaml#/getUser"


  # Auth paths
  /auth/signup:
    $ref: "./paths/auth.yaml#/signup"

  /auth/signin:
    $ref: "./paths/auth.yaml#/signIn"


  # Team paths
  /team:
    $ref: "./paths/team.yaml#/createTeam"

  /team/{teamId}/members:
    $ref: "./paths/team.yaml#/manageTeamMembers"

  /team/{teamId}:
    $ref: "./paths/team.yaml#/manageTeamDetails"

  /team/{teamId}/member/{memberId}/role/{roleDto}:
    $ref: "./paths/team.yaml#/manageTeamMembersRole"


  # Order paths
  /team/{teamId}/order:
    $ref: "./paths/order.yaml#/order"

  /order/{orderId}/status/{orderStatusDto}:
    $ref: "./paths/order.yaml#/setOrderStatus"

  /order/{orderId}:
    $ref: "./paths/order.yaml#/manageOrderDetails"


  # Order paths
  /order/{orderId}/product:
    $ref: "./paths/product.yaml#/addProduct"

  /product/{productId}:
    $ref: "./paths/product.yaml#/manageProductDetails"
